version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codesa-front-dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start
    stdin_open: true
    tty: true
